name: 'Sajak & Farki'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7172094830311835
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9ecf1'
    - '#aea69c'
    - '#08080a'
    - '#02505c'
    - '#7a563e'
  brandStrength: 0.375
  lightness: 0.7872127457521856
  saturation: 0.6857580083888024
  rhythmicContrast: 0.20287643908523023
purpose: []
